### ISSUE TITLE
solve the problems using python3

### ISSUE THREAD

**Issue by zkx06111** [JohnLins/LeetCode#2]
I noticed that your current `1.py` looks like this
```python
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
```

while it should be like this if you select the python3 option on leetcode:

```
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
```

From now on, could you solve the problems in python 3? Since that's what our project is in.

**Comment by JohnLins** [comment]
Okay, I will do this from now on starting with 019.py
